In [41]:
import json
import warnings

In [49]:
# with open("test.json", "r") as f:
#     data = json.load(f)
data  = [
    [1,1,1,1,1],
    [1,9,9,9,1],
    [1,9,1,9,1],
    [1,9,9,9,1],
    [1,1,1,1,1]
]

In [51]:
result = np.array(data.copy())
for x, row in enumerate(data):
    for y, cell in enumerate(row):
        if cell > 8:
            print(x, y)
            print(result[x-1:x+2][y-1:y+2])
            result[x-1:x+2][y-1:y+2] += 1
        result[x][y]=cell + 1
   



1 1
[[2 2 2 2 2]
 [2 9 9 9 1]
 [1 9 1 9 1]]
1 2
[[ 3 10 10 10  2]
 [ 2 10  2 10  2]]
1 3
[[ 3 11  3 11  3]]
2 1
[[ 4 11 10 10  2]
 [ 2 12  4 12  4]
 [ 1  9  9  9  1]]
2 3
[[ 2 10 10 10  2]]
3 1
[[ 3 10  2 10  2]
 [ 2 11 11 11  3]
 [ 1  1  1  1  1]]
3 2
[[ 3 10 12 12  4]
 [ 2  2  2  2  2]]
3 3
[[3 3 3 3 3]]


In [45]:
result

array([[ 3,  3,  3,  3,  3],
       [ 5, 12, 11, 11,  3],
       [ 4, 11,  3, 11,  3],
       [ 4, 11, 10, 10,  2],
       [ 2,  2,  2,  2,  2]])

In [39]:
test = np.array([1, 2, 3, 4])
test + 1

array([2, 3, 4, 5])

In [12]:
import numpy as np

data_np = np.array(data)
result_np = data_np + 1
print(result_np)

[[ 2  2  2  2  2]
 [ 2 10 10 10  2]
 [ 2 10  2 10  2]
 [ 2 10 10 10  2]
 [ 2  2  2  2  2]]


In [44]:
vert = 0
horiz = 0
depth = 0
result = {}
for datum in data:
    for i in range(len(data[0])):
        if not result.get(i):
            result[i] = ""
        result[i] += datum[i]

t = ""
for idx, i in result.items():
    t += str(bit_counter(i))
t
# print(t)
gamma_dec = int(t, 2)
tt = ''.join('1' if b == '0' else '0' for b in t)
epsilon_dec = int(tt, 2)
# print(gamma_dec, epsilon_dec)
power_rate = gamma_dec * epsilon_dec
power_rate

198

In [51]:

# CO2 scrubber
print(data)
holder = data.copy()
rt = []
for i in range(len(data[0])):
    for datum in holder:
        # print(datum[i])
        if int(datum[i]) % 2 == i % 2:
            rt.append(datum)
    holder = rt.copy()
    rt = []
print(holder)
int(holder[0], 2)

['00100', '11110', '10110', '10111', '10101', '01111', '00111', '11100', '10000', '11001', '00010', '01010']
['01010']


10